spring:
  application:
    name: sales-system

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/sales_system}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:8080}